### ISSUE TITLE
BUG: Cannot view files in some situations.

### ISSUE THREAD

**Issue by jameswalmsley** [VitalElement/AvalonStudio#464] opened 2017-07-16 06:41 UTC
Open a file which generates an error in the error list.
Close the file (the error list remains).

Click on the error, it wont be able to display the file anymore.

Furthermore using solution explorer cannot re-open the file either.

The new caching system??

**Comment by danwalmsley** [comment] 2017-07-16 09:38
Ok found the cause, firstly errors should have been removed from error list when tab is closed, this is fixed.

Cause is that clang-format binary need chmod+x on linux... we need to sort out, how our dependencies like clang-format libclang etc are distributed, currently msbuild takes them from the nuget package at compile time, but doesnt chmod! not sure nuget supports this so we have a couple of options:

1) manually chmod in code, files we know have to be chmodded in the plugin that uses these files.
2) we distribute these as a package (tools->packages) and the plugin that requires these files (cpp language service) manually installs them the first time they are used.

im leaning towards number 2) since we eventually will move to a model where these plugins dont come with the main ide and you choose what you want at initial setup.

#443 would also be solved by this.

**Comment by danwalmsley** [comment] 2017-07-16 09:58
This might be a good indicator we should implement first use setup screen, where user selects the type of development they are interested and packages are downloaded.

This will require a system for debugging extensions, i.e. Your extension project won't need Avalon studio sources, bit you can launch Avalon studio and debug your extension under visual studio or in future Avalon studio itself

**Comment by danwalmsley** [comment] 2017-07-16 09:59
Also #434 is related to this.

**Comment by danwalmsley** [comment] 2018-05-26 10:52
Definitely fixed now.

**Closed by danwalmsley** 2018-05-26 10:52 UTC
